#!/usr/bin/python
# coding: UTF-8
"""
@author: CaiKnife

Triangular, pentagonal, and hexagonal
Problem 45
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle        Tn=n(n+1)/2     1, 3, 6, 10, 15, ...
Pentagonal      Pn=n(3n1)/2     1, 5, 12, 22, 35, ...
Hexagonal       Hn=n(2n1)       1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
"""
from euler import triangle_number, pentagon_number, hexagon_number

p = set(pentagon_number(i) for i in range(1, 100000))
h = set(hexagon_number(i) for i in range(1, 100000))

for i in range(286, 100000):
    t = triangle_number(i)
    if t in p and t in h:
        print t
        break
